"""
Proposed Road Graph — model_lab

Dataclass for road network proposals generated by model_lab graph generators.

Distinct from model_lab.training.road_graph_extractor.RoadGraph (which
extracts graphs from existing simulation output). This ProposedGraph
represents a design intent to be evaluated by the layout engine.

No production code is modified.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple


# ---------------------------------------------------------------------------
# Node types
# ---------------------------------------------------------------------------

NODE_INTERSECTION = "intersection"
NODE_DEAD_END     = "dead_end"
NODE_ENTRY        = "entry"
NODE_TERMINUS     = "terminus"   # planned end-point not yet on boundary


# ---------------------------------------------------------------------------
# Core dataclasses
# ---------------------------------------------------------------------------

@dataclass
class GraphNode:
    id:   int
    x:    float
    y:    float
    type: str = NODE_TERMINUS   # intersection | dead_end | entry | terminus

    def dist(self, other: "GraphNode") -> float:
        dx, dy = self.x - other.x, self.y - other.y
        return math.sqrt(dx * dx + dy * dy)

    def to_dict(self) -> dict:
        return {"id": self.id, "x": round(self.x, 2), "y": round(self.y, 2), "type": self.type}


@dataclass
class GraphEdge:
    from_node: int
    to_node:   int
    coords:    List[Tuple[float, float]]   # polyline vertices including endpoints
    length_ft: float = 0.0

    def __post_init__(self) -> None:
        if self.length_ft == 0.0 and self.coords:
            total = 0.0
            for i in range(len(self.coords) - 1):
                dx = self.coords[i+1][0] - self.coords[i][0]
                dy = self.coords[i+1][1] - self.coords[i][1]
                total += math.sqrt(dx*dx + dy*dy)
            self.length_ft = total

    def to_dict(self) -> dict:
        return {
            "from": self.from_node,
            "to":   self.to_node,
            "length_ft": round(self.length_ft, 2),
        }


@dataclass
class ProposedGraphMetrics:
    node_count:          int = 0
    edge_count:          int = 0
    intersection_count:  int = 0
    dead_end_count:      int = 0
    entry_count:         int = 0
    total_road_length_ft: float = 0.0
    avg_edge_length_ft:  float = 0.0
    road_density_ft_per_acre: float = 0.0
    topology_class:      str = "unknown"

    def to_dict(self) -> dict:
        return {
            "node_count":             self.node_count,
            "edge_count":             self.edge_count,
            "intersection_count":     self.intersection_count,
            "dead_end_count":         self.dead_end_count,
            "entry_count":            self.entry_count,
            "total_road_length_ft":   round(self.total_road_length_ft, 2),
            "avg_edge_length_ft":     round(self.avg_edge_length_ft, 2),
            "road_density_ft_per_acre": round(self.road_density_ft_per_acre, 4),
            "topology_class":         self.topology_class,
        }


@dataclass
class ProposedGraph:
    """
    A candidate road network generated by model_lab graph generators.

    Fields
    ------
    nodes:          graph nodes (intersections, entries, dead-ends)
    edges:          road segments connecting nodes
    entry_points:   node ids where the network meets the parcel boundary
    metrics:        pre-computed graph metrics
    generator_type: which generator produced this graph
    params:         generator parameters for mutation / reproducibility
    parcel_area_sqft: parcel area (for density calculations)
    """
    nodes:          List[GraphNode]              = field(default_factory=list)
    edges:          List[GraphEdge]              = field(default_factory=list)
    entry_points:   List[int]                    = field(default_factory=list)
    metrics:        ProposedGraphMetrics         = field(default_factory=ProposedGraphMetrics)
    generator_type: str                          = "unknown"
    params:         Dict                         = field(default_factory=dict)
    parcel_area_sqft: float                      = 0.0

    # ---------------------------------------------------------------------------
    # Geometry helpers
    # ---------------------------------------------------------------------------

    def node_by_id(self, nid: int) -> Optional[GraphNode]:
        for n in self.nodes:
            if n.id == nid:
                return n
        return None

    def to_centerlines(self):
        """Convert edges to Shapely LineString objects."""
        from shapely.geometry import LineString
        lines = []
        for edge in self.edges:
            if len(edge.coords) >= 2:
                lines.append(LineString(edge.coords))
        return lines

    def compute_metrics(self, parcel_area_sqft: float = 0.0) -> None:
        """Recompute metrics from current nodes/edges."""
        area = parcel_area_sqft or self.parcel_area_sqft
        degrees = {n.id: 0 for n in self.nodes}
        for e in self.edges:
            degrees[e.from_node] = degrees.get(e.from_node, 0) + 1
            degrees[e.to_node]   = degrees.get(e.to_node,   0) + 1

        intersections = sum(1 for n in self.nodes if n.type == NODE_INTERSECTION)
        dead_ends     = sum(1 for n in self.nodes if n.type in (NODE_DEAD_END, NODE_TERMINUS))
        entries       = sum(1 for n in self.nodes if n.type == NODE_ENTRY)
        total_len     = sum(e.length_ft for e in self.edges)
        avg_len       = total_len / len(self.edges) if self.edges else 0.0
        acres         = area / 43560.0 if area > 0 else 1.0

        self.metrics = ProposedGraphMetrics(
            node_count=len(self.nodes),
            edge_count=len(self.edges),
            intersection_count=intersections,
            dead_end_count=dead_ends,
            entry_count=entries,
            total_road_length_ft=total_len,
            avg_edge_length_ft=avg_len,
            road_density_ft_per_acre=total_len / acres,
            topology_class=self.generator_type,
        )

    def to_dict(self) -> dict:
        return {
            "generator_type": self.generator_type,
            "params":         self.params,
            "nodes":          [n.to_dict() for n in self.nodes],
            "edges":          [e.to_dict() for e in self.edges],
            "entry_points":   self.entry_points,
            "metrics":        self.metrics.to_dict(),
        }

    def __repr__(self) -> str:
        m = self.metrics
        return (
            f"ProposedGraph({self.generator_type}  "
            f"nodes={m.node_count}  edges={m.edge_count}  "
            f"road_len={m.total_road_length_ft:.0f}ft  "
            f"density={m.road_density_ft_per_acre:.0f}ft/ac)"
        )
